"""empty message

Revision ID: 9e5981a583c2
Revises: 
Create Date: 2018-06-02 20:09:31.370625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5981a583c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameEmpresa', sa.String(length=64), nullable=False),
    sa.Column('clientCNPJ', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_clientCNPJ'), 'client', ['clientCNPJ'], unique=True)
    op.create_index(op.f('ix_client_nameEmpresa'), 'client', ['nameEmpresa'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codTask', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_codTask'), 'task', ['codTask'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_matricula'), 'users', ['matricula'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codProject', sa.Integer(), nullable=False),
    sa.Column('nameProject', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_codProject'), 'project', ['codProject'], unique=True)
    op.create_index(op.f('ix_project_nameProject'), 'project', ['nameProject'], unique=True)
    op.create_table('binding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binding')
    op.drop_index(op.f('ix_project_nameProject'), table_name='project')
    op.drop_index(op.f('ix_project_codProject'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_matricula'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_codTask'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_client_nameEmpresa'), table_name='client')
    op.drop_index(op.f('ix_client_clientCNPJ'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
